# -*- coding: utf-8 -*-
"""Emergency service.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GqAkEtIIOm_Mwlh3YdFZALqfn90KO7iM
"""



import pandas as pd

df = pd.read_csv('/content/emergency_service_routing_with_timestamps.csv')

display(df.head())
display(df.info())

print("Incident Type Distribution:")
display(df['Incident_Type'].value_counts())

print("\nResponse Time Descriptive Statistics:")
display(df['Response_Time'].describe())

print("\nMean Response Time by Incident Severity:")
display(df.groupby('Incident_Severity')['Response_Time'].mean())

print("\nMean Response Time by Traffic Congestion:")
display(df.groupby('Traffic_Congestion')['Response_Time'].mean())

print("\nMean Response Time by Region Type:")
display(df.groupby('Region_Type')['Response_Time'].mean())

missing_values = df.isnull().sum()
print("Columns with missing values before handling:")
display(missing_values[missing_values > 0])

if 'Weather_Impact' in df.columns and df['Weather_Impact'].isnull().any():
    mode_weather_impact = df['Weather_Impact'].mode()[0]
    df['Weather_Impact'].fillna(mode_weather_impact, inplace=True)
    print(f"\nFilled missing 'Weather_Impact' with mode: {mode_weather_impact}")


print("\nColumns with missing values after handling:")
display(df.isnull().sum()[df.isnull().sum() > 0])


categorical_cols = df.select_dtypes(include='object').columns.tolist()
categorical_cols.remove('Timestamp')
if 'Label' in categorical_cols:
    categorical_cols.remove('Label')

print(f"\nCategorical columns to encode: {categorical_cols}")

# Apply one-hot encoding to categorical columns
df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)
print("\nDataFrame after one-hot encoding:")
display(df.head())


df['Timestamp'] = pd.to_datetime(df['Timestamp'])

df['Hour_of_Day'] = df['Timestamp'].dt.hour
df['Day_of_Week'] = df['Timestamp'].dt.dayofweek
df['Month'] = df['Timestamp'].dt.month
df['Year'] = df['Timestamp'].dt.year
print("\nDataFrame after extracting time-based features:")
display(df.head())

df.drop('Timestamp', axis=1, inplace=True)
print("\nDataFrame after dropping Timestamp column:")
display(df.head())


print("\nData types after preprocessing:")
display(df.info())

from sklearn.model_selection import train_test_split
import lightgbm as lgb
from sklearn.metrics import classification_report, accuracy_score

X = df.drop('Label', axis=1)
y = df['Label']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print("Training data shape:", X_train.shape)
print("Testing data shape:", X_test.shape)

lgbm = lgb.LGBMClassifier(random_state=42)
lgbm.fit(X_train, y_train)

print("\nLightGBM model trained successfully.")

y_pred = lgbm.predict(X_test)

print("\nModel Evaluation:")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

from sklearn.metrics import accuracy_score, classification_report

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f}")

class_report = classification_report(y_test, y_pred)
print("\nClassification Report:")
print(class_report)

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import lightgbm as lgb
from sklearn.metrics import accuracy_score, classification_report

X = df.drop('Label', axis=1)
y = df['Label']

label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

X_train, X_test, y_train_encoded, y_test_encoded = train_test_split(
    X, y_encoded, test_size=0.2, random_state=42, stratify=y_encoded
)

model = lgb.LGBMClassifier(objective='multiclass', num_class=len(label_encoder.classes_), random_state=42)
model.fit(X_train, y_train_encoded)

y_pred_encoded = model.predict(X_test)

y_pred = label_encoder.inverse_transform(y_pred_encoded)

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f}")

class_report = classification_report(y_test, y_pred)
print("\nClassification Report:")
print(class_report)

import pickle

with open('lgbm_model.pkl', 'wb') as f:
    pickle.dump(model, f)

with open('label_encoder.pkl', 'wb') as f:
    pickle.dump(label_encoder, f)

print("Trained model and label encoder saved successfully.")

import pickle
import pandas as pd

try:
    with open('lgbm_model.pkl', 'rb') as f:
        loaded_model = pickle.load(f)
    with open('label_encoder.pkl', 'rb') as f:
        loaded_label_encoder = pickle.load(f)
    print("Model and label encoder loaded successfully.")
except FileNotFoundError:
    print("Error: Model or label encoder file not found.")
    loaded_model = None
    loaded_label_encoder = None


def predict_emergency_response(new_incident_data: pd.DataFrame) -> str:
    """
    Predicts the optimal emergency response strategy for new incident data.

    Args:
        new_incident_data: A pandas DataFrame containing the features of the
                           new incident, in the same format as the training data
                           before one-hot encoding and time feature extraction.

    Returns:
        The predicted emergency response label (e.g., 'Ambulance Only',
        'Drone Only', 'Hybrid Dispatch').
        Returns an error message if the model or encoder are not loaded.
    """
    if loaded_model is None or loaded_label_encoder is None:
        return "Error: Model or label encoder not loaded."

    # 3. Preprocess the incoming data (similar to training data preprocessing)
    # Ensure 'Timestamp' is datetime and extract features
    if 'Timestamp' in new_incident_data.columns:
        new_incident_data['Timestamp'] = pd.to_datetime(new_incident_data['Timestamp'])
        new_incident_data['Hour_of_Day'] = new_incident_data['Timestamp'].dt.hour
        new_incident_data['Day_of_Week'] = new_incident_data['Timestamp'].dt.dayofweek
        new_incident_data['Month'] = new_incident_data['Timestamp'].dt.month
        new_incident_data['Year'] = new_incident_data['Timestamp'].dt.year
        new_incident_data = new_incident_data.drop('Timestamp', axis=1)
    else:

        pass

    original_categorical_cols = ['Incident_Severity', 'Incident_Type', 'Region_Type',
                                 'Traffic_Congestion', 'Weather_Condition', 'Road_Type',
                                 'Emergency_Level', 'Dispatch_Coordinator', 'Weather_Impact']



    new_incident_data_encoded = pd.get_dummies(new_incident_data, columns=original_categorical_cols, drop_first=True)


    train_cols = X_train.columns

    missing_cols = set(train_cols) - set(new_incident_data_encoded.columns)
    for c in missing_cols:
        new_incident_data_encoded[c] = 0

    new_incident_data_processed = new_incident_data_encoded[train_cols]



    predicted_label_encoded = loaded_model.predict(new_incident_data_processed)

    predicted_label = loaded_label_encoder.inverse_transform(predicted_label_encoded)

    return predicted_label[0]

import pandas as pd

def chatbot_predict_response():
    """
    Simulates a chatbot conversation to collect incident data and predict
    the emergency response.
    """
    print("Hello! I am the Emergency Response Chatbot. Please provide details about the incident.")

    incident_type = input("Incident Type (e.g., Accident, Cardiac Arrest, Fire, Other): ")
    incident_severity = input("Incident Severity (Low, Medium, High): ")
    region_type = input("Region Type (Rural, Suburban, Urban): ")
    traffic_congestion = input("Traffic Congestion (Low, Moderate, High): ")
    weather_condition = input("Weather Condition (Clear, Rainy, Stormy, Snowy): ")
    drone_availability = input("Is a drone available? (Available, Unavailable): ")
    ambulance_availability = input("Is an ambulance available? (Available, Unavailable): ")
    battery_life = float(input("Drone Battery Life (%): "))
    air_traffic = input("Air Traffic (Low, Medium, High): ")
    hospital_capacity = int(input("Hospital Capacity (%): "))
    distance_to_incident = float(input("Distance to Incident (km): "))
    number_of_injuries = int(input("Number of Injuries: "))
    specialist_availability = input("Is a specialist available? (Available, Unavailable): ")
    road_type = input("Road Type (Highway, Local Road, Unpaved Road): ")
    emergency_level = input("Emergency Level (Minor, Major, Critical): ")
    drone_speed = float(input("Drone Speed (km/h): "))
    ambulance_speed = float(input("Ambulance Speed (km/h): "))
    payload_weight = float(input("Drone Payload Weight (kg): "))
    fuel_level = float(input("Ambulance Fuel Level (%): "))
    weather_impact = input("Weather Impact (None, Moderate, Severe): ")
    dispatch_coordinator = input("Dispatch Coordinator (AI, Human): ")

    new_incident_data = pd.DataFrame([{
        'Timestamp': pd.Timestamp.now(),
        'Incident_Severity': incident_severity,
        'Incident_Type': incident_type,
        'Region_Type': region_type,
        'Traffic_Congestion': traffic_congestion,
        'Weather_Condition': weather_condition,
        'Drone_Availability': drone_availability,
        'Ambulance_Availability': ambulance_availability,
        'Battery_Life': battery_life,
        'Air_Traffic': air_traffic,
        'Response_Time': 0, # Response Time is the target in the original data, but a feature in the model's input. Use a placeholder or consider how this feature is handled. For prediction, it should likely not be used directly as it's an outcome. However, the trained model used it as a feature. This might indicate a potential issue in the model's feature set if Response_Time is not known at the time of dispatch. For now, setting it to 0 or an average might be necessary if the model truly requires it. Re-examining the model training step (d694260b and cLbnXzxI9phC) shows Response_Time was included in X. This is likely incorrect for a real-world prediction scenario where Response_Time is unknown. For this exercise, I will include it with a placeholder, but this needs refinement in a production system. Let's use the mean from the original data analysis (around 15) as a more representative placeholder than 0.
        'Hospital_Capacity': hospital_capacity,
        'Distance_to_Incident': distance_to_incident,
        'Number_of_Injuries': number_of_injuries,
        'Specialist_Availability': specialist_availability,
        'Road_Type': road_type,
        'Emergency_Level': emergency_level,
        'Drone_Speed': drone_speed,
        'Ambulance_Speed': ambulance_speed,
        'Payload_Weight': payload_weight,
        'Fuel_Level': fuel_level,
        'Weather_Impact': weather_impact,
        'Dispatch_Coordinator': dispatch_coordinator
    }])


    predicted_response = predict_emergency_response(new_incident_data)

    print(f"\nBased on the information provided, the recommended emergency response is: {predicted_response}")

chatbot_predict_response()